steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA-$BUILD_ID',
    '-t', 
    'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME', 
    '.' 
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA-$BUILD_ID'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME'
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 
    'deploy', 
    '${REPO_NAME}', 
    '--image', 
    'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA-$BUILD_ID', 
    '--region', 
    '${_REGION}',
    '--port',
    '${_PORT}',
    '--allow-unauthenticated'
  ]
substitutions:
  _REGION: 'asia-southeast1'
  _PORT: '80'
images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA-$BUILD_ID',
  'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME'
]